# Generated by Django 6.0.5 on 2026-05-21 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('kcal', models.IntegerField(help_text='kCal per 100g')),
                ('protein', models.DecimalField(decimal_places=2, help_text='Protein (g) per 100g', max_digits=6)),
                ('carbs', models.DecimalField(decimal_places=2, help_text='Carbohydrates (g) per 100g', max_digits=6)),
                ('fat', models.DecimalField(decimal_places=2, help_text='Fat (g) per 100g', max_digits=6)),
                ('fiber', models.DecimalField(decimal_places=2, help_text='Fiber (g) per 100g', max_digits=6)),
                ('season', models.CharField(choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Autumn', 'Autumn'), ('Winter', 'Winter'), ('All Year', 'All Year')], default='All Year', help_text='Best seasonality for this ingredient', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, default='')),
                ('prep_time', models.IntegerField(default=0, help_text='Preparation time in minutes')),
                ('cook_time', models.IntegerField(default=0, help_text='Cooking time in minutes')),
                ('servings', models.IntegerField(default=1)),
                ('culinary_origin', models.CharField(help_text='E.g., Italian, Japanese, French', max_length=100)),
                ('meal_type', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Dessert', 'DESSERT'), ('Snack', 'Snack'), ('Other', 'Other')], default='Dinner', max_length=20)),
                ('season', models.CharField(choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Autumn', 'Autumn'), ('Winter', 'Winter'), ('All Year', 'All Year')], default='All Year', help_text='Best seasonality for this recipe', max_length=20)),
                ('instructions', models.JSONField(default=list, help_text="A list of step-by-step instructions (e.g., ['Step 1...', 'Step 2...'])")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=8)),
                ('unit', models.CharField(choices=[('g', 'grams (g)'), ('ml', 'milliliters (ml)'), ('pcs', 'pieces (pcs)'), ('tbsp', 'tablespoons (tbsp)'), ('tsp', 'teaspoons (tsp)')], default='g', max_length=10)),
                ('weight_in_grams', models.DecimalField(decimal_places=2, help_text="Equivalent weight in grams for nutritional calculations. Auto-populates for 'g' and 'ml'.", max_digits=8)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='recipes.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='recipes.recipe')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', through='recipes.RecipeIngredient', to='recipes.ingredient'),
        ),
    ]
